name: Deploy to Dev

on:
  push:
    branches: [develop]

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Integration
        run: echo "→ Deploy to integration environment (simuliert)"
